# Generated by Django 5.1.4 on 2024-12-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('designation', models.CharField(max_length=255)),
                ('jobTitle', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('indroduction', models.TextField()),
                ('skills', models.TextField()),
                ('previousRole', models.TextField()),
                ('previousCompany', models.TextField()),
                ('achievements', models.TextField()),
                ('approach', models.TextField()),
            ],
        ),
    ]
