# Generated by Django 5.1.4 on 2024-12-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverletterinput',
            old_name='indroduction',
            new_name='introduction',
        ),
    ]
