version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles

db:
  image: postgres:15-alpine
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 5

volumes:
  postgres_data:
  static_volume:
